name: Deploy to EC2

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
        NPM_HOME: ${{ secrets.NPM_HOME }}
        HOST_DIRECTORY: ${{ secrets.HOST_DIRECTORY }}
        BUILD_DIRECTORY: ${{ secrets.BUILD_DIRECTORY }}
      run: |
        echo "$PRIVATE_KEY" > github-ec2.pem && chmod 600 github-ec2.pem
        ssh -o StrictHostKeyChecking=no -i github-ec2.pem ${USER}@${HOST}

        echo "Starting deploy to EC2 instance..."
        git pull
        echo "Successfully pulled repo"
        npm install
        echo "Successfully installed dependencies"
        npm run build
        echo "Npm has been built"
        if ls $HOST_DIRECTORY; then
          sudo rm -r $HOST_DIRECTORY
        fi
        sudo mkdir $HOST_DIRECTORY
        sudo mv -v $BUILD_DIRECTORY $HOST_DIRECTORY
        echo "Successfully deployed to nealetw.com!"
        '
      
